#!/system/bin/sh

LOG_DIR=/data/data/

while true
do
	# send keyevent KEYCODE_ENTER
	input keyevent 66

	hciconfig hci0|grep RUNNING
	while [ $? -ne 0 ]
	do
		sleep 1
		hciconfig hci0|grep RUNNING
	done

	# send keyevent KEYCODE_ENTER
	input keyevent 66

	hciconfig hci0|grep DOWN
	while [ $? -ne 0 ]
	do
		sleep 1
		hciconfig hci0|grep DOWN
	done
done
