#!/system/bin/sh

log_path="/sdcard/klogcat/"`date +%F`
screencap_path="$log_path/screencap/"

switch_channel()
{
	RANGE=2
	count=0
	event=3

	echo "###################################################################"
	echo "#                                                                 #"
	echo "#                     switch channel test                         #"
	echo "#                                                                 #"
	echo "###################################################################"

	while true
	do
		num=$RANDOM
		let "num %= $RANGE"
		let count+=1
		echo $count

		if [ $num -eq 1 ]
		then
			# send keyevent F9
			echo "send key F9"
			# input keyevent F9
			sendevent /dev/input/event$event 1 67 1
			sendevent /dev/input/event$event 0 0 0
			sendevent /dev/input/event$event 1 67 0
			sendevent /dev/input/event$event 0 0 0
			#sleep 20
		else

			# send keyevent F11
			echo "send key F11"
			# input keyevent F11
			sendevent /dev/input/event$event 1 87 1
			sendevent /dev/input/event$event 0 0 0
			sendevent /dev/input/event$event 1 87 0
			sendevent /dev/input/event$event 0 0 0
			#sleep 20
		fi
	done
}

btsnoop_enable()
{
	bt_stack="/system/etc/bluetooth/bt_stack.conf"
	mount -o remount,rw /system
	busybox sed -i 's/BtSnoopLogOutput=false/BtSnoopLogOutput=true/g' $bt_stack
}

main()
{
	# make sure directory exist
	if [ ! -d "$log_path" ]; then
		mkdir $log_path
	fi

	echo "log directory: $log_path"
	echo "screencap directory: $screencap_path"

	# remove outdated traces.txt
	if [ -f /data/anr/traces.txt ]; then
		rm /data/anr/traces.txt
	fi

	# enable btsnoop for hci debug
	btsnoop_enable
}

main
