#!/system/bin/sh

root_path="/data"
log_path="$root_path/klogcat/"`date +%F`
screencap_path="$log_path/screencap/"
plain_text_mail="false"

mailserver="74.208.5.15"
mailfrom="fudong@mail.com"

switch_channel()
{
	RANGE=2
	count=0
	event=3

	echo "###################################################################"
	echo "#                                                                 #"
	echo "#                     switch channel test                         #"
	echo "#                                                                 #"
	echo "###################################################################"

	while true
	do
		num=$RANDOM
		let "num %= $RANGE"
		let count+=1
		echo $count

		if [ $num -eq 1 ]
		then
			# send keyevent F9
			echo "send key F9"
			# input keyevent F9
			sendevent /dev/input/event$event 1 67 1
			sendevent /dev/input/event$event 0 0 0
			sendevent /dev/input/event$event 1 67 0
			sendevent /dev/input/event$event 0 0 0
			#sleep 20
		else

			# send keyevent F11
			echo "send key F11"
			# input keyevent F11
			sendevent /dev/input/event$event 1 87 1
			sendevent /dev/input/event$event 0 0 0
			sendevent /dev/input/event$event 1 87 0
			sendevent /dev/input/event$event 0 0 0
			#sleep 20
		fi
	done
}

onoff_test()
{
	count=0

	while true
	do
		# send keyevent KEYCODE_ENTER
		input keyevent 66
		sleep 1
		input keyevent 66
		sleep 17

		let count+=1
		echo tested $count times
	done
}

# get current screen shot
gtv_screencast()
{
	if [ ! -d "$screencap_path" ]; then
		mkdir -p $screencap_path
	fi
	screencap "$screencap_path/android-`date +%F-%H-%M-%S`.png"
}

# enable btsnoop for hci debug
btsnoop_enable()
{
	bt_stack="/system/etc/bluetooth/bt_stack.conf"
	mount -o remount,rw /system
	busybox sed -i 's/BtSnoopLogOutput=false/BtSnoopLogOutput=true/g' $bt_stack
	busybox sed -i 's/BtSnoopFileName=\/sdcard\/btsnoop_hci.log/BtSnoopFileName=\/data\/misc\/bluedroid\/btsnoop_hci.log/g' $bt_stack

	# dump more log
	busybox sed -i 's/TRC_BTM=2/TRC_BTM=5/g' $bt_stack
	busybox sed -i 's/TRC_HCI=2/TRC_HCI=5/g' $bt_stack
	busybox sed -i 's/TRC_L2CAP=2/TRC_L2CAP=5/g' $bt_stack
	busybox sed -i 's/TRC_SDP=2/TRC_SDP=5/g' $bt_stack
	busybox sed -i 's/TRC_GATT=2/TRC_GATT=5/g' $bt_stack
	busybox sed -i 's/TRC_SMP=2/TRC_SMP=5/g' $bt_stack
	busybox sed -i 's/TRC_BTAPP=2/TRC_BTAPP=5/g' $bt_stack
	busybox sed -i 's/TRC_BTIF=2/TRC_BTIF=5/g' $bt_stack
}

gtv_get_bdaddr()
{
	cat /sys/devices/virtual/bluetooth/hci0/address > $log_path/bdaddr.txt
}

gtv_kmsg()
{
	echo `date +%F-%H-%M-%S` > $log_path/kmsg.txt
	cat /proc/kmsg >>$log_path/kmsg.txt&
}

gtv_getprop()
{
	getprop > $log_path/getprop.txt
}

gtv_getevent()
{
	echo `date +%F-%H-%M-%S` > $log_path/getevent.txt
	getevent -lt >> $log_path/getevent.txt&
}

gtv_getip()
{
	netcfg |grep eth0|busybox cut -d " " -f37
}

gtv_get_macaddr()
{
	# mac address
	netcfg |grep eth0|busybox cut -d " " -f40 > $log_path/macaddr.txt
}

gtv_bluetooth_status()
{
	adb shell am start -n "com.android.settings/.bluetooth.BluetoothSettings"
	gtv_screencast
}

gtv_pack_log()
{
	cd $root_path
	busybox tar cvf klogcat.tar klogcat
	busybox bzip2 -zvv klogcat.tar
}

gtv_internet_available()
{
	ping -c 2 g.cn
	if [ $? -eq 0 ]
	then
		echo "internet available"
	else [ $? -eq 2 ]
		echo "ping: unknown host g.cn"
	fi
}

# send plain text message using busybox sendmail applet
busybox_sendmail()
{
	echo "###################################################################"
	echo "#                                                                 #"
	echo "#                    send mail to module owner                    #"
	echo "#                  using busybox swiss army knife                 #"
	echo "#                                                                 #"
	echo "###################################################################"

	mailto="fudongbai@gmail.com"

	# need a new line between subject and mail body
	echo "Subject: someone has issue" > $log_path/mail.txt
	echo "" >> $log_path/mail.txt
	cat $log_path/getprop.txt >> $log_path/mail.txt
	busybox sendmail -v -S $mailserver -f $mailfrom \
		-au"fudong@mail.com" -ap"qwerty123" $mailto < $log_path/mail.txt
}

# send plain text message using busybox sendmail applet
busybox_sendmail_with_attachment()
{
	echo "###################################################################"
	echo "#                                                                 #"
	echo "#                   send mail to module owner                     #"
	echo "#               using busybox makemime and sendmail               #"
	echo "#                                                                 #"
	echo "###################################################################"


	mailto="fudong@mail.com"
	subject="Someone has issue"

	busybox makemime -a "Subject: $subject" \
		-o $root_path/attachment \
		$root_path/klogcat.tar.bz2
	busybox sendmail -v -S $mailserver -f $mailfrom \
		-au"fudong@mail.com" -ap"qwerty123" \
		$mailto < $root_path/attachment
}

# remove all the temp files
gtv_cleanup()
{
	rm $root_path/klogcat.tar*
	rm $root_path/attachment

	# remove outdated traces.txt
	if [ -f /data/anr/traces.txt ]; then
		rm /data/anr/traces.txt
	fi

	kill -15 `busybox pidof getevent`
}

gtv_post_processing()
{
	# bluetooth hci log
	cp $root_path/misc/bluedroid/btsnoop_hci.log $log_path/
	cp $root_path/misc/bluedroid/bt_config.* $log_path/

	# pack all the log file
	gtv_pack_log

	# see if we can send mail to module owner
	#gtv_internet_available

	# send mail to module owner

	if [ $1 = "true" ]; then
		echo "sending plain text mail"
		busybox_sendmail
	else
		echo "sending mail with attachment"
		busybox_sendmail_with_attachment
	fi
}

gtv_prepare()
{
	# set timezone
	setprop persist.sys.timezone Asia/Shanghai

	# make sure directory exist
	if [ ! -d "$log_path" ]; then
		mkdir -p $log_path
	fi

	echo "log directory: $log_path"
	echo "screencap directory: $screencap_path"

	# get ethernet mac address
	gtv_get_macaddr

	# get bluetooth adapter mac address
	# gtv_get_bdaddr

	# get device info
	gtv_getprop
}

gtv_bluetooth_log()
{
	# get kernel log
	gtv_kmsg

	# bluetooth settings
	gtv_bluetooth_status
}

gtv_remote_log()
{
	# getevent
	gtv_getevent
}

main()
{
	gtv_post_processing plain_text_mail
	#gtv_cleanup

	while true; do
		echo "Do you wish to enable bluedroid log? [Yes/No]"
		read yesno
		case $yesno in
			[Yy]* ) btsnoop_enable;
				break;;
			[Nn]* ) exit;;
			* ) echo "Please answer yes or no.";;
		esac
	done
}

main
